<?
	include_once("lib/conf.common.php");
	include_once("lib/class.cStudent.php");

	$student = new cStudent($mysqlhost, $mysqluser, $mysqlpass, $mysqldb, $studentTable, $applicantTable, $accountTable);
	$student->connectDatabase();

	$email = array();
	$email[] = "leeaeq@bc.edu";
	$email[] = "jpark5@binghamton.edu";
	$email[] = "paulng83@gmail.com";
	$email[] = "zachary_y_green@yahoo.com";
	$email[] = "sejun87@hotmail.com";
	$email[] = "wson0827@hotmail.com";
	$email[] = "kyhi89278@naver.com";
	$email[] = "bhahn2@buffalo.edu";
	$email[] = "eseo@andrew.cmu.edu";
	$email[] = "JANETTEM@HANMI.COM";
	$email[] = "eugeneng@live.com";
	$email[] = "babusaja@naver.com";
	$email[] = "jackyfat1000@yahoo.co.uk";
	$email[] = "linayi5@gmail.com";
	$email[] = "chiyungyou@yahoo.com";
	$email[] = "jsstiny@msn.com";
	$email[] = "victory.lee@utoronto.ca";
	$email[] = "cfskorea@foreignstudy.co.kr";
	$email[] = "chongsm1@hotmail.com";
	$email[] = " luvjill420@aol.com";
	$email[] = "seeung3@hotmail.com";
	$email[] = "jcpak562@yahoo.com";
	$email[] = "idri41@Gmail.com";
	$email[] = "jingonboy@hotmail.com";
	$email[] = "u0603008@nus.edu.sg";
	$email[] = "jungsong@eden.rutgers.edu";
	$email[] = "U0704771@nus.edu.sg";
	$email[] = "spark54@wisc.edu";
	$email[] = "dustin_wie@hotmail.com";
	$email[] = "garred@ufl.edu";
	$email[] = "sean71574@juno.com";
	$email[] = "lch2200@hotmail.com";
	$email[] = "tankuankhoon@gmail.com";
	$email[] = "jonathano@nus.edu.sg";
	$email[] = "jh5451@yahoo.co.kr";
	$email[] = "u0600502@nus.edu.sg";
	$email[] = "hkang@bates.edu";
	$email[] = "floreyhe@yahoo.ca";
	$email[] = "sechki7@hotmail.com";
	$email[] = "hka31@sfu.ca";
	$email[] = "mswift@asialearn.org";
	$email[] = "jackson@apc.sg";
	$email[] = "mswift@asialearn.org";
	$email[] = "ahybmef@nottingham.ac.uk";
	$email[] = "jkdw71@etczone.com";
	$email[] = "andytsui@hkusua.hku.hk";
	$email[] = "yickchun@hku.hk";
	$email[] = "lionheart1234086@yahoo.com.hk";
	$email[] = "michaelchang7@gmail.com";
	$email[] = "gaoting@nus.edu.sg";
	$email[] = "bys6c2@umsl.edu";
	$email[] = "john.lichten@conncoll.edu";
	$email[] = "mistaho@gmail.com";
	$email[] = "peterk_etc@hotmail.com";
	$email[] = "alee50@uic.edu";
	$email[] = "nari@uni-bonn.de";
	$email[] = "ejju@emory.edu";
	$email[] = "hazuki_otake0802@hotmail.com";
	$email[] = "raindrops248@yahoo.co.jp";
	$email[] = "sunghye86@hotmail.com";
	$email[] = "nurul109@hotmail.com";
	$email[] = "higashiz@hawaii.edu";
	$email[] = "yyan112@ec.auckland.ac.nz";
	$email[] = "marianne@nus.edu.sg";
	$email[] = "u0702773@nus.edu.sg";
	$email[] = "grassipark@aol.com";
	$email[] = "sjbae@learnlink.emory.edu";
	$email[] = "srhee01@msn.com";
	$email[] = "yelim15@interchange.ubc.ca";
	$email[] = "inhea527@hotmail.com";
	$email[] = "devica@nus.edu.sg";
	$email[] = "shuang_hu87@hotmail.com";
	$email[] = "gxstar87@hotmail.com";
	$email[] = "u0607468@nus.edu.sg";
	$email[] = "leesj@bu.edu";
	$email[] = "jsong30@jhu.edu";
	$email[] = "dq0820@hotmail.com";
	$email[] = "ckmc@hku.hk";
	$email[] = "mswift@asialearn.org";
	$email[] = "jinju@msu.edu";
	$email[] = "jyu27@uiuc.edu";
	$email[] = "ekim10@wellesley.edu";
	$email[] = "like_vpvjalsxm@hotmail.com";
	$email[] = "chahn07@vt.edu";
	$email[] = "gcpak@uci.edu";
	$email[] = "emoon2@uic.edu";
	$email[] = "kellyhur@ufl.edu";
	$email[] = "hkry5@mizzou.edu";
	$email[] = "cloud_happy@hotmail.com";
	$email[] = "Kate.Connolly@utoronto.ca";
	$email[] = "u0604835@nus.edu.sg";
	$email[] = "ajs10@ufl.edu";
	$email[] = "mhs47@georgetown.edu";
	$email[] = "u0708447@nus.edu.sg";
	$email[] = "cybergal_lyw@hotmail.com";
	$email[] = "sophia427@gmail.com";
	$email[] = "messier035@hotmail.com";
	$email[] = "hlee83@emory.edu";
	$email[] = "aylee@indiana.edu";
	$email[] = "kimnkl@bc.edu";
	$email[] = "felicia.koh@nus.edu.sg";
	$email[] = "huipang@nus.edu.sg";
	$email[] = "u0505018@nus.edu.sg";
	$email[] = "qw4@georgetown.edu";
	$email[] = "janejanejanejanejane@gmail.com";
	$email[] = "youngn921@myway.com";
	$email[] = "puai_jia_yan@hotmail.com";
	$email[] = "estherpeh@nus.edu.sg";
	$email[] = "karamriver@hotmail.com";
	$email[] = "u0708568@nus.edu.sg";
	$email[] = "aga.baranowska@utoronto.ca";
	$email[] = "t.huitian@gmail.com";

	for ($i = 0; $i < count($email); $i++) {
		if (trim($email[$i]) != "") {
			$flag = $student->updatePassword1($email[$i], "0000");
			echo "" . $email[$i] . " - " . $flag . "<br>";
		}
	}

	$student->closeDatabase();
	unset($student);
?>